### ISSUE TITLE
buildroot integration problem

### ISSUE THREAD

**Issue by Sjoerd82** [pycontribs/tendo#22] opened 2017-10-05 16:57 UTC
I've added tendo to buildroot, but I get an installation error, and I'm not sure whether or not the problem lies with the tendo installer or elsewhere.

Buildroot gives me back (I think from tendo's setup.py) "distutils.errors.DistutilsError: Could not find suitable distribution fro Requirement.parse('six').

Initially I thought that perhaps the "six" package is a dependency, but after adding this to buildroot, I still get the error message. Even tried installing it locally, but no luck.

**Comment by ssbarnea** [comment] 2018-04-04 06:43
Closing this because is does not contain enough information about platform and the way to reproduce it. Feel free to reopen it once you have all the information. My guess is that if you cannot find six package, you have bigger problems to address.

**Closed by ssbarnea** 2018-04-04 06:43 UTC
