### ISSUE TITLE
Exception ImportError: 'No module named sys' in <bound method SingleInstance.__del__...

### ISSUE THREAD

**Issue by nhooey** [pycontribs/tendo#13] opened 2016-01-30 01:19 UTC
When I make a Python package with `setuptools`, then install it in a virtualenv and run it, I get this error:

```
Exception ImportError: 'No module named sys' in <bound method SingleInstance.__del__ of 
<tendo.singleton.SingleInstance instance at 0x108618488>> ignored
```

Here are the project files:

``` python
#!/usr/bin/env python
# setup.py

from setuptools import setup

setup(
    name='run-ansible-pull',
    version='1.0',
    description='Runs Ansible Pull and reports to Sensu',
    author='Author',
    author_email='author@somewhere.com',
    packages=['singleton_test'],
    entry_points = {
        'console_scripts': [
            'singleton-test = singleton_test:main',
        ],
    },
    install_requires=[
        'tendo==0.2.8',
    ],
 )
```

``` python
# singleton_test/__init__.py
from tendo import singleton

me = singleton.SingleInstance()

def main():
    print "Hello, World!"
```

And here is the full transcript:

```
$ virtualenv .venv && source .venv/bin/activate
$ python setup.py install && singleton-test
running install
running bdist_egg
running egg_info
creating run_ansible_pull.egg-info
writing requirements to run_ansible_pull.egg-info/requires.txt
writing run_ansible_pull.egg-info/PKG-INFO
writing top-level names to run_ansible_pull.egg-info/top_level.txt
writing dependency_links to run_ansible_pull.egg-info/dependency_links.txt
writing entry points to run_ansible_pull.egg-info/entry_points.txt
writing manifest file 'run_ansible_pull.egg-info/SOURCES.txt'
reading manifest file 'run_ansible_pull.egg-info/SOURCES.txt'
writing manifest file 'run_ansible_pull.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.10-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/singleton_test
copying singleton_test/__init__.py -> build/lib/singleton_test
creating build/bdist.macosx-10.10-x86_64
creating build/bdist.macosx-10.10-x86_64/egg
creating build/bdist.macosx-10.10-x86_64/egg/singleton_test
copying build/lib/singleton_test/__init__.py -> build/bdist.macosx-10.10-x86_64/egg/singleton_test
byte-compiling build/bdist.macosx-10.10-x86_64/egg/singleton_test/__init__.py to __init__.pyc
creating build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying run_ansible_pull.egg-info/PKG-INFO -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying run_ansible_pull.egg-info/SOURCES.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying run_ansible_pull.egg-info/dependency_links.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying run_ansible_pull.egg-info/entry_points.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying run_ansible_pull.egg-info/requires.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
copying run_ansible_pull.egg-info/top_level.txt -> build/bdist.macosx-10.10-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/run_ansible_pull-1.0-py2.7.egg' and adding 'build/bdist.macosx-10.10-x86_64/egg' to it
removing 'build/bdist.macosx-10.10-x86_64/egg' (and everything under it)
Processing run_ansible_pull-1.0-py2.7.egg
Removing /private/tmp/singleton-test/.venv/lib/python2.7/site-packages/run_ansible_pull-1.0-py2.7.egg
Copying run_ansible_pull-1.0-py2.7.egg to /private/tmp/singleton-test/.venv/lib/python2.7/site-packages
run-ansible-pull 1.0 is already the active version in easy-install.pth
Installing singleton-test script to /private/tmp/singleton-test/.venv/bin

Installed /private/tmp/singleton-test/.venv/lib/python2.7/site-packages/run_ansible_pull-1.0-py2.7.egg
Processing dependencies for run-ansible-pull==1.0
Searching for tendo==0.2.8
Best match: tendo 0.2.8
Processing tendo-0.2.8-py2.7.egg
tendo 0.2.8 is already the active version in easy-install.pth

Using /private/tmp/singleton-test/.venv/lib/python2.7/site-packages/tendo-0.2.8-py2.7.egg
Finished processing dependencies for run-ansible-pull==1.0
Hello, World!
Exception ImportError: 'No module named sys' in <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance instance at 0x108618488>> ignored
```
##

**Comment by ssbarnea** [comment] 2016-02-01 18:00
I have not idea why `import sys` would ever fail, seems really weird.

**Comment by nhooey** [comment] 2016-02-12 21:02
Do you have any idea how to fix it? @ssbarnea

**Comment by nhooey** [comment] 2016-02-12 21:04
This happens with Python 2.7.11 installed from Homebrew on Mac OS as of today.

Are you able to reproduce it with the example I gave? If so, what's your environment?

**Comment by panofish** [comment] 2016-03-08 22:12
I just did a pip install tendo and when I used pyinstaller to compile an exe of my python code ... I got this same error.  Fortunately, the error also says "ignored" and my exe is still created and still appears to work correctly with the tendo logic.

**Comment by mvonthron** [comment] 2017-01-03 16:44
For what it's worth: I add the same error and explicitly calling `del instance` fixed the problem. 

That being said, IMHO relying on `__init__` and `__del__` is not the correct approach for such a task, it would be much better to work with `with` statements instead.

**Comment by ssbarnea** [comment] 2018-04-03 18:59
I am going to close this bug but I will reopen it if you can provide a snippet to reproduce it but not one that does run code inside the `__init__.py` of a module, something that may endup executed while the module is installed, which is very-very wrong.

Many things changed since original bug was raise which makes me think is safe to close.

**Closed by ssbarnea** 2018-04-03 18:59 UTC
