### ISSUE TITLE
Exception in SingleInstance.__del__

### ISSUE THREAD

**Issue by thorr18** [pycontribs/tendo#14] opened 2016-03-04 00:28 UTC
Perhaps harmless.

```
mySystem:myappdir myuser$ nosetests-3.4
SingleInstance lockfile: /var/folders/8m/6dsl12z52g7b_9f4kh1yb0s40000gn/T/-usr-local-bin-nosetests-3-.lock
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
Exception ignored in: <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance object at 0x104af9c18>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tendo/singleton.py", line 63, in __del__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
mySystem:myappdir myuser$ 
```

Or when commenting out the two imports suggested by @efairon in #12 : 

```
mySystem:myappdir myuser$ nosetests-3.4
SingleInstance lockfile: /var/folders/8m/6dsl12z52g7b_9f4kh1yb0s40000gn/T/-usr-local-bin-nosetests-3-.lock
.
----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
'NoneType' object is not iterable
Exception ignored in: <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance object at 0x102f7cbe0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tendo/singleton.py", line 83, in __del__
SystemExit: -1
mySystem:myappdir myuser$ 
```

Running my app seems to work, with tendo keeping other instances from starting, but that ignored exception shows up again when I exit using ctrl-c

```
mySystem:myappdir myuser$ python3 myappdir/myapp.py
SingleInstance lockfile: /var/folders/8m/6dsl12z52g7b_9f4kh1yb0s40000gn/T/-Users-myuser-factory-Py-myapp-myapp-myapp-.lock
please Control-C to exit myapp
RUNNING myapp
^CCLOSING myapp
Exception ignored in: <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance object at 0x10ced8128>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tendo/singleton.py", line 63, in __del__
ImportError: import of 'sys' halted; None in sys.modules
mySystem:myappdir myuser$ 
```
##

**Comment by alanlun516** [comment] 2016-04-22 08:39
I have the same issue with Python 3.5.1.
I have to exit program by pressing Control-C.
It leads hanging my program...

**Comment by ssbarnea** [comment] 2016-04-30 15:54
I am not able to replicate this so I am closing it. If you can make an unittest that replicates it or even better a PR with both the replication and the fix it would be great.

**Comment by wolfgang-noichl** [comment] 2017-08-05 17:23
Not sure how to put this into a unittest (since python is already closing when the error is triggered), but this file reproduces the issue (run like `python test.py`):

```python
from tendo import singleton
me = singleton.SingleInstance()

import time
time.sleep(5)
```

This will trigger something like (Linux, python3.5.3, something similar on windows):
```
Exception ignored in: <bound method SingleInstance.__del__ of <tendo.singleton.SingleInstance object at 0x7f79474927f0>>
Traceback (most recent call last):
  File "...", line 69, in __del__
ImportError: import of 'sys' halted; None in sys.modules
```
even though there should not be any output at all.

When closing a Qt5 application where I use this, I get something similar to @thorr18; I think the reason is the same. [This](https://stackoverflow.com/questions/33178216/import-error-on-python-3-4-exit-tendo#comment60400512_33178216) is probably relevant.

**Comment by underdpt** [comment] 2018-07-06 15:43
I can confirm this on python 3.5.3 on Ubuntu 14.04.5 LTS

**Comment by glezo1** [comment] 2018-07-22 09:58
Same here: 
confirmed with @wolfgang-noichl  test.py , running on python 3.4.8, , CentOS 6.9 x86_64

**Comment by wolfgang-noichl** [comment] 2019-02-26 14:58
@ssbarnea you may want to reopen this, no? ;)

**Comment by ssbarnea** [comment] 2019-02-27 08:31
FYI, py34 is not supported. Feel free to make a PR.

**Closed** 2019-05-23 13:52 UTC
